Feature/request access token
Octopus-Indonesia/grabclient pull request #1
Opened 2021-08-19 19:05 UTC by neoreids

2021-08-20 00:17 UTC, rizkyarlin requested changes

2021-08-20 00:17 UTC, rizkyarlin commented on .gitignore
> -# User-specific stuff
Ini jgn dihapus kak. Karena sy ada .idea karena pakai pycharm ka

2021-08-20 00:17 UTC, rizkyarlin commented on src/grabclient/constant.py
> +REDIS_KEY_ACCESS_TOKEN = "grab_access_token"
"GRAB_EXPRESS_ACCESS_TOKEN"

2021-08-20 00:21 UTC, neoreids commented on .gitignore
> +.idea
Ini?

2021-08-23 03:06 UTC, rizkyarlin approved these changes

2021-08-23 03:07 UTC, merged